x-environment:
  - &service

networks:
  migration_networks:
    driver: bridge

services:
  migration:
    platform: linux/amd64
    restart: "no"
    ports:
      - 8080:80
    build:
      context: ./
      target: development
    environment:
      APP_ENV: prod
      APP_DEBUG: 1
    volumes:
      - ./:/project
    networks:
      - migration_networks

  mysql:
    platform: linux/amd64
    image: mysql:8.0
    container_name: migration_mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: migration_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - migration_networks

  dependencies:
    platform: linux/amd64
    restart: "no"
    build:
      context: ./
      target: development
    entrypoint: /usr/bin/composer
    command: install
    volumes:
      - ./:/project:delegated
