version: '3.8'

x-environment:
  - &service


services:
  migration:
    platform: linux/amd64
    restart: "no"
    ports:
      - 80:80
    build:
      context: ./
      target: development
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - ./:/project:delegated

