x-environment:
  - &service

services:
  migration:
    platform: linux/amd64
    restart: "no"
    ports:
      - 8080:80
    build:
      context: ./
      target: development
    environment:
      APP_ENV: prod
      APP_DEBUG: 1
    volumes:
      - ./:/project
  dependencies:
    platform: linux/amd64
    restart: "no"
    build:
      context: ./
      target: development
    entrypoint: /usr/bin/composer
    command: install
    volumes:
      - ./:/project:delegated
