<?php

namespace MBMigration\Builder\BrizyComponent;

class BrizyMinistryBrandsSermonLayout extends BrizyComponent
{
    public function __construct($collectionUri)
    {
        $data = [
            "type" => "MinistryBrandsSermonLayout",
            "value" => [
                "_styles" => [
                    "ministryBrandsSermonLayout",
                ],
                "_id" => "mnyzlmadozermdrhbhwhgtkpdprlcplzxhuc",
                "filterBgColorType" => "solid",
                "tempFilterBgColorType" => "solid",
                "filterBgColorHex" => "#d9d9d9",
                "filterBgColorOpacity" => 0.5,
                "tempFilterBgColorOpacity" => 1,
                "filterBgColorPalette" => "color3",
                "tempFilterBgColorPalette" => "",
                "filterGradientColorHex" => "#000000",
                "filterGradientColorOpacity" => 1,
                "tempFilterGradientColorOpacity" => 1,
                "filterGradientColorPalette" => "",
                "tempFilterGradientColorPalette" => "",
                "filterGradientType" => "linear",
                "filterGradientStartPointer" => 0,
                "filterGradientFinishPointer" => 100,
                "filterGradientActivePointer" => "finishPointer",
                "filterGradientLinearDegree" => 90,
                "filterGradientRadialDegree" => 0,
                "tabsState" => "normal",
                "source" => "/collection_types/1650123",
                "detailPage" => "{{ brizy_dc_url_post id=\"{$collectionUri}\" }}",
                "detailPageTitle" => "Sermon Detail",
                "detailPageButtonText" => "",
                "inputBorderStyle" => "solid",
                "tempInputBorderStyle" => "solid",
                "inputBorderColorHex" => "#000000",
                "inputBorderColorOpacity" => 1,
                "tempInputBorderColorOpacity" => 1,
                "inputBorderColorPalette" => "color8",
                "tempInputBorderColorPalette" => "",
                "inputBorderWidthType" => "grouped",
                "inputBorderWidth" => 1,
                "tempInputBorderWidth" => 1,
                "inputBorderTopWidth" => 1,
                "tempInputBorderTopWidth" => 1,
                "inputBorderRightWidth" => 1,
                "tempInputBorderRightWidth" => 1,
                "inputBorderBottomWidth" => 1,
                "tempInputBorderBottomWidth" => 1,
                "inputBorderLeftWidth" => 1,
                "tempInputBorderLeftWidth" => 1,
                "filterTypographyFontStyle" => "paragraph",
                "inputHex" => "#000000",
                "inputOpacity" => 1,
                "inputPalette" => "color5",
                "tempInputOpacity" => 1,
                "tempInputPalette" => "",
                "titleTypographyFontStyle" => "heading4",
                "titleColorHex" => "#707070",
                "titleColorOpacity" => 1,
                "titleColorPalette" => "color4",
                "tempTitleColorOpacity" => 1,
                "tempTitleColorPalette" => "",
                "hoverTitleColorHex" => "#c8eb49",
                "hoverTitleColorOpacity" => 1,
                "hoverTitleColorPalette" => "color3",
                "tempHoverTitleColorOpacity" => 1,
                "tempHoverTitleColorPalette" => "",
                "typographyFontStyle" => "heading6",
                "colorHex" => "#707070",
                "colorOpacity" => 1,
                "colorPalette" => "color7",
                "tempColorOpacity" => 1,
                "tempColorPalette" => "",
                "metaLinksColorHex" => "#E9B44C",
                "metaLinksColorOpacity" => 1,
                "metaLinksColorPalette" => "color4",
                "tempMetaLinksColorOpacity" => 1,
                "tempMetaLinksColorPalette" => "",
                "hoverMetaLinksColorHex" => "#c8eb49",
                "hoverMetaLinksColorOpacity" => 1,
                "hoverMetaLinksColorPalette" => "color3",
                "tempHoverMetaLinksColorOpacity" => 1,
                "tempHoverMetaLinksColorPalette" => "",
            ],
        ];


        parent::__construct($data);
    }
}