export const model = {
  "font-family": undefined,
  "font-family-type": "uploaded",
  "font-weight": undefined,
  "font-size": undefined,
  "line-height": undefined,
  "letter-spacing": undefined,
  "font-style": "",
  "border-color-hex": undefined,
  "border-color-opacity": 1,
  "border-color-palette": "",
  "border-width": 1,
  "color-hex": undefined,
  "color-opacity": 1,
  "color-palette": "",
  "bg-color-hex": undefined,
  "bg-color-opacity": 1,
  "bg-color-palette": "",
  uppercase: false
};
